### ISSUE TITLE
Mac OS install failing for Big Sur (11.5.1)

### ISSUE THREAD

**Issue by madAndroid** [tilt-dev/tilt#4859] opened 2021-08-13 13:40 UTC
### Expected Behavior
Tilt is installed using the curl | bash script

### Current Behavior
The following error occurs:

```
# brew install tilt-dev/tap/tilt
==> Installing tilt from tilt-dev/tap
==> Downloading https://github.com/tilt-dev/tilt/releases/download/v0.22.3/tilt.0.22.3.mac.x86_64.tar.gz
Already downloaded: /Users/andrew/Library/Caches/Homebrew/downloads/249bae387460add66399b63fc32949cac53c1cf9f5171aaa1c565cb43921f38c--tilt.0.22.3.mac.x86_64.tar.gz
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
Did you mean?  paths
```

### Steps to Reproduce
Follow install steps from https://docs.tilt.dev/install.html on Mac OS 11.5.1 (BigSur)
```
curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
```

#### About Your Use Case

I cannot install tilt using the homebrew package

**Comment by nicks** [comment] 2021-08-13 14:45
thanks for reporting @madAndroid ! Can you run `brew doctor` and post the output? that's a good tool for diagnosing brew problems.

**Comment by dboshardy** [comment] 2021-08-17 19:40
I'm also having this issue and this is the output of `brew doctor` for me:


```bash
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 12.5.


Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 12.5.


Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  git
  python@3.9

Warning: /usr/bin occurs before /usr/local/bin in your PATH.
This means that system-provided programs will be used instead of those
provided by Homebrew. Consider setting your PATH so that
/usr/local/bin occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.zshrc

The following tools exist at both paths:
  vim
  ctags
  vi
  vimdiff
  python3
  pip3
  view
  git-shell
  git

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

**Comment by nicks** [comment] 2021-08-17 19:47
hi @dboshardy ! thanks for the output. I think it's telling you how to fix it. You need to run

```
softwareupdate --all --install --force
```

From googling around, my impression is that this error is saying that you have incompatible versions of Homebrew and Xcode Command Line Tools. Lots of other projects are seeing the same problem, cf
https://github.com/rbenv/ruby-build/issues/1434
https://github.com/schollz/croc/issues/235

Try that and see if it helps? Closing as I don't see any indication this is a problem with the Tilt Homebrew formula.

**Comment by dboshardy** [comment] 2021-08-17 19:47
@nicks 

output:

```bash
$ softwareupdate --all --install --force
Software Update Tool

Finding available software
No updates are available.
```

**Closed by nicks** 2021-08-17 19:47 UTC
Labels: bug

**Comment by nicks** [comment] 2021-08-17 19:58
ha! sorry. That's what I get for assuming that the `brew doctor` recommendations were correct! :sweat_smile: 

But assuming that the warning about `Your Command Line Tools are too outdated` is the root cause here, this is probably not the best place to get advice troubleshooting this. Our advice is not going to be any better than `brew doctor`'s.

In the meantime, we also have alternative ways to install Tilt without Homebrew:
https://docs.tilt.dev/install.html#alternative-installations

**Comment by dboshardy** [comment] 2021-08-17 20:04
Thanks for the alternative install link. I was trying to find something like that on the site and must have missed it.

**Comment by madAndroid** [comment] 2021-08-19 13:48
Apologies for the late response @nicks - thanks for the heads up, installing the latest commandline tools did indeed fix the issue, and I'm able to install Tilt now via the tap 👍
