### ISSUE TITLE
Live update does not work

### ISSUE THREAD

**Issue by paneq** [tilt-dev/tilt#3511] opened 2020-06-25 11:03 UTC
Assuming Tiltfile:

```
docker_build(
  'chronicles',
  '/Users/rupert/develop/chronicles',
  live_update=[
    sync('/Users/rupert/develop/chronicles/.testbox', '/.testbox')
  ]
)
k8s_yaml('k8s_chronicles.yaml')
```

When I edit `/Users/rupert/develop/chronicles/.testbox/`
I see 

```
   chronicles │ Will copy 1 file(s) to container: e960ff8344                                                                     ↑
   chronicles │ - '/Users/rupert/develop/chronicles/.testbox/rpc.rb' --> '/.testbox/rpc.rb'                                
   chronicles │   → Container e960ff8344 updated!       
```

in logs, but when I run `kubectl exec deploy/chronicles -c chronicles cat .testbox/rpc.rb`, I see that the content is not updated.

Info about environment:

```
$ tilt version
v0.14.3, built 2020-06-12

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by landism** [comment] 2020-06-25 15:42
Hm, I'm not aware of Tilt having had any bugs where it said it was syncing files but actually wasn't. The first thing I'd do is double-check a couple of things to confirm what's happening:
1. `kubectl exec deploy/chronicles -c chronicles cat .testbox/rpc.rb` is using a path relative to the container's working directory (which may be `/`, so it doesn't matter, but just to be sure) - what if you make the path absolute instead? i.e., `kubectl exec deploy/chronicles -c chronicles cat /.testbox/rpc.rb`
2. When Tilt logs `chronicles │ Will copy 1 file(s) to container: e960ff8344`, does that match the `chronicles` container of `deploy/chronicles`?

**Comment by paneq** [comment] 2020-06-25 16:17
Thank you for looking into the matter.

> When Tilt logs chronicles │ Will copy 1 file(s) to container: e960ff8344, does that match the chronicles container of deploy/chronicles?

Yes. That I already checked too.

> what if you make the path absolute instead? i.e., kubectl exec deploy/chronicles -c chronicles cat /.testbox/rpc.rb

I can give it a try tomorrow.

Maybe the problem is in the dot in `.testbox`.

**Comment by nicks** [comment] 2021-07-14 17:17
I'm going to close this as not-reproducible, since we haven't gotten any other reports of this and there's not much else we can do with the info we have...happy to re-open if you want to investigate further

**Closed by nicks** 2021-07-14 17:17 UTC
Labels: needs repro case
