### ISSUE TITLE
Tilt not ignoring folders and triggers rebuild

### ISSUE THREAD

**Issue by traxx10** [tilt-dev/tilt#6240] opened 2023-10-06 05:50 UTC
### Expected Behavior
I have a monorepo setup using turbo repo.  My project structure looks like this. whenever i change a file in **testfolder** or **apps/web-dashboard** it shouldn't trigger a docker rebuild in any of my docker builds in any of the services. 

![Screenshot 2023-10-06 at 6 21 53 AM](https://github.com/tilt-dev/tilt/assets/31565764/3afc5de8-f9d2-4df6-b889-b5ac4530eb62)

### Current Behavior
whenever i change a file in **testfolder** or **apps/web-dashboard** it triggers a rebuild in all the running docker images instead of ignoring those folders. I have tried .tiltignore, watch_settings etc. None of it works
![Screenshot 2023-10-06 at 6 49 42 AM](https://github.com/tilt-dev/tilt/assets/31565764/f282a93a-a459-427e-b676-871860a707e9)

This is one of my services, you can see that it says "Found files(s) not matching any spec" which triggers a rebuild. I don't want that folder or file to even be watched or at all or at least it shouldn't trigger a rebuild

<img width="1105" alt="Screenshot 2023-10-06 at 6 51 34 AM" src="https://github.com/tilt-dev/tilt/assets/31565764/fadf1331-15ab-43ee-9702-3c9efaf469ec">

**Comment by nicks** [comment] 2023-10-06 14:15
thanks for the report! but this ticket doesn't have enough information for us to repro your problem.

Possible debugging tips:
- have you seen this guide? https://docs.tilt.dev/file_changes
- does .tiltignore work for you in the example project? https://github.com/tilt-dev/tilt-example-html

**Comment by traxx10** [comment] 2023-10-06 14:49
Hello @nicks , thanks for the quick reply,

- I have seen the guide 
- I am using this example and yes I did also add a .tiltignore file but it doesn't work. https://github.com/tilt-dev/tilt-avatars

I added a folder called test in the root directory, but whenever I change any file in that folder, the whole application rebuilds. I don't want the application to rebuild whenever i change anything in the test folder. I want the folder to be ignored.

This is an example repo - https://github.com/traxx10/tilt-avatars

**Comment by nicks** [comment] 2023-10-06 18:12
Any chance you're using macos, and you're checking out code into a directory that's mixing capitalization? E.g. you cd into it as ~/src but the "real" directory name is ~/Src. There are some bugs on macos around how it's filesystem APIs handle case-sensitivity, see https://github.com/tilt-dev/tilt/issues/5271#issuecomment-991195056

**Comment by nicks** [comment] 2023-10-09 14:00
hmmm thanks for the example repo above. i was not able to repro though -- editing files in test/ were ignored.

can you try:
1) editing a file that you think should be ignored
2) posting the output of `tilt get filewatches -o yaml` to this issue?
that will give us detailed information about where it thinks the event is coming from.

**Comment by traxx10** [comment] 2023-10-09 14:24
Thanks for the reply. Here's a screenshot and a video as well.

You can see that as soon as i save, the image gets rebuilt, i don't want it to be rebuilt on every file change as i have a monorepo setup.

![Screenshot 2023-10-09 at 3 18 56 PM](https://github.com/tilt-dev/tilt/assets/31565764/3907f174-3e46-4107-b655-9785be0b9a80)

https://github.com/tilt-dev/tilt/assets/31565764/37533a89-6274-4ec2-81e6-67f364ce236d

**Comment by nicks** [comment] 2023-10-09 14:39
marking this as a duplicate of https://github.com/tilt-dev/tilt/issues/5271

ya, this is a casing problem -- the problem is that macos is storing the directory as `/Users/chucksben/Desktop` but you're cd'ing into it as `/Users/chucksben/desktop`. if you rename it to `desktop` the problem will go away.

**Closed by nicks** 2023-10-09 14:39 UTC
Labels: bug, needs repro case
