### ISSUE TITLE
image pruner does not prune properly labeled custom_build images

### ISSUE THREAD

**Issue by dnephin** [tilt-dev/tilt#6131] opened 2023-06-02 18:54 UTC
Hello tilt team!

We use tilt with a `Tiltfile` where all image building is done with `custom_build`. We're aware of #4023 so we've been building images with `--label=dev.tilt.gc=true`. We've noticed despite the label,  the `tilt` image pruner is not effective.

I believe there are two problems that prevent `DockerPruner` from removing these images.

The first is `!state.HasDockerBuild()` in this line:

https://github.com/tilt-dev/tilt/blob/542020055dd9629ce1122957d162be619184ccfd/internal/engine/dockerprune/docker_pruner.go#L86-L88

`HasDockerBuild` checks if any of the `ImageTarget`'s are `DockerBuild`, but all of ours are `CustomBuild`, so that check always returns `false`, and the `DockerPruner.OnChange` always exits before doing any work.

The second problem is in the check for multiple `RepoTags` on an image:

https://github.com/tilt-dev/tilt/blob/542020055dd9629ce1122957d162be619184ccfd/internal/engine/dockerprune/docker_pruner.go#L205-L210

I understand this is to avoid the case where `docker image rm <imageID>` fails because the image ID has multiple tags. The problem is that because tilt always uses a unique image tag, it's pretty common (at least for us) to have images like this:

```
REPOSITORY      TAG                         IMAGE ID       CREATED        SIZE
service-image   tilt-20230602110058-29047   6e0e8c5d397e   4 hours ago    897MB
service-image   tilt-20230602115032-23931   6e0e8c5d397e   4 hours ago    897MB
service-image   tilt-20230602125517-16785   6e0e8c5d397e   4 hours ago    897MB
```

There are multiple "RepoTags" for the same image ID. This will happen any time someone closes tilt and then runs `tilt up` again, or if they click the "trigger update" in tilt UI. As soon as there are 2 images with the same ID, the `DockerPruner` refuses to remove any of them. Over time this can build up to a lot of images not being removed and running out of space.

### Proposal

To address these problems, I propose:

1. `HasDockerBuild` can be changed to check `if targ.IsDockerBuild() || targ.IsCustomBuild()`. `HasDockerBuild` is only called in this one place, so this shouldn't impact any other logic.
2. The `deleteOldImages` logic can be changed slightly to delete by `RepoTag` instead of image ID (https://docs.docker.com/engine/api/v1.43/#tag/Image/operation/ImageDelete supports names as well as ID). Removing by name will simply remove that tag when there are multiple tags, and will remove the image when there is only a single tag left.

I'm happy to submit PRs for these changes. The first one is trivial, and the second should be a relatively small localized change in `docker_pruner.go`. I'll just need to figure a test case.

**Comment by nicks** [comment] 2023-06-02 19:45
thanks for the report! I'm gong to mark this as a duplicate of https://github.com/tilt-dev/tilt/issues/4023, so that there's one place for the discussion.

**Closed by nicks** 2023-06-02 19:45 UTC
Labels: bug
