### ISSUE TITLE
CRDs + live update

### ISSUE THREAD

**Issue by lisamburns** [tilt-dev/tilt#4141] opened 2021-01-29 01:40 UTC
### Current Behavior
Hello, I am trying to use knative with the live update feature and having issues.
I configure the kNative CRD with the `k8s_kind` function per the docs: https://docs.tilt.dev/custom_resource.html
Then I attempt to configure file sync and live_update using `docker_build_with_restart` to specify the entrypoint for restarting the container (docs here: https://github.com/tilt-dev/tilt-extensions/tree/master/restart_process)
Is this supported? Sounds like it's not supported in the error message, in which case this is more of a feature request than a bug but just wanted to confirm.

### Expected Behavior
Ideally this would enable live updating on the CRD.

### Current Behavior
I get this error:
```
Build Failed: could not inject command [/tilt-restart-wrapper --watch_file=/.restart-proc sh -c ./main.sh] into entity: example-html. No container found matching ref: dev.local/example-html-image:tilt-691ac4101bc8c0bb. Note: command overrides only supported on containers with images, not on CRDs
```

### Steps to Reproduce
Here is the snippets from my Tiltfile:
```
k8s_kind('Service', api_version='serving.knative.dev/v1',
         image_json_path='{.spec.template.spec.containers[].image}')
k8s_resource('example-html', port_forwards=8000, resource_deps=['deploy'],
             extra_pod_selectors=[{'app': 'example-html'}])
sync_src = sync('.', '/app/')
docker_build_with_restart('dev.local/example-html-image', '.', entrypoint="./main.sh", live_update=[sync_src])
```

#### `tilt doctor` Output
Tilt: v0.18.5, built 2021-01-22
System: darwin-amd64
---
Docker
- Host: tcp://127.0.0.1:55018
- Version: 1.41
- Builder: 2
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: docker
- Version: v1.20.0
- Cluster Local Registry: none

#### About Your Use Case
Attempting to use live update with knative

**Comment by landism** [comment] 2021-01-29 15:46
Yeah, you're right, it's not currently supported with CRDs. Sorry about that!

We describe some alternatives in our [live update docs](https://docs.tilt.dev/live_update_reference.html#workarounds-for-restarting-your-process) if you want to give those a shot and/or have any questions about those.

**Comment by lizzthabet** [comment] 2022-04-20 18:26
i'm closing this as a duplicate of #4776.

**Closed by lizzthabet** 2022-04-20 18:26 UTC
Labels: duplicate, enhancement
