### ISSUE TITLE
Snapshot does not work / unexpected character / 500 internal server error

### ISSUE THREAD

**Issue by FFdhorkin** [tilt-dev/tilt#3194] opened 2020-04-08 21:10 UTC
Clicking the "get link" button doesn't do anything. I do see this in the logs when I click it, though:
>Error creating snapshot: posting snapshot failed. status: 500 Internal Server Error, response: error creating snapshot

Also noticed this in my console:
>SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data" HUD.tsx:195:32
    sendSnapshot HUD.tsx:195

**Comment by victorwuky** [comment] 2020-04-08 21:41
Thanks @FFdhorkin for logging this!

**Comment by victorwuky** [comment] 2020-04-08 22:00
That UI is also not very friendly since there isn't immediate feedback. We should add some type of loading UI as the snapshot is being generated. The bug here may be related to problems with load / too many services. And we need better designs to help the user and gracefully degrade the experience.

**Comment by FFdhorkin** [comment] 2020-04-08 22:15
> That UI is also not very friendly since there isn't immediate feedback. We should add some type of loading UI as the snapshot is being generated. The bug here may be related to problems with load / too many services. And we need better designs to help the user and gracefully degrade the experience.

I'm skeptical about it being load or too many services, but it's possible. I'm trying to transition our local environment from docker-compose to k8s (w/ Tilt) to better match our production environments. Things aren't working yet, so the logs are mostly errors about some services not being able to talk to one another. (We've got roughly a dozen.)

**Comment by jazzdan** [comment] 2020-04-09 14:56
I think this is probably the problem where if there are too many logs it exceeds the GRPC message size limit in the backend,

**Comment by jazzdan** [comment] 2020-04-09 17:17
Oh, I think @landism mentioned a while back that this is actually a limit to the amount of data that can be in one field in Firestore.

**Comment by andymartin-sch** [comment] 2020-04-22 14:56
> I think this is probably the problem where if there are too many logs it exceeds the GRPC message size limit in the backend

yeah this is not reproducible for us at the beginning of our `tilt up` runs but is consistently reproducible later on after the logs have grown in size

it would be nice if the "take snapshot" functionality would grab the last N lines from each service such that it always stays under the limit

**Comment by FFdhorkin** [comment] 2020-04-23 18:04
> > I think this is probably the problem where if there are too many logs it exceeds the GRPC message size limit in the backend
> 
> yeah this is not reproducible for us at the beginning of our `tilt up` runs but is consistently reproducible later on after the logs have grown in size past ~2M
> 
> it would be nice if the "take snapshot" functionality would grab the last N lines from each service such that it always stays under the limit

This repros for us almost immediately upon tilt up, but that's probably because our logs are very spammy. I've never managed to take a snapshot.

**Comment by victorwuky** [comment] 2020-06-01 18:03
We are aiming to work on https://github.com/tilt-dev/tilt/issues/3128 in the coming weeks, and plan to work on investigating this bug and fixing it at the same time.

**Comment by FFdhorkin** [comment] 2020-06-01 18:13
I haven't had a chance to work on getting Tilt working with our project since April, but I'm anticipating trying again next week sometime. 

If you ping this issue when you believe you have a fix, I'd be happy to confirm whether the snapshots are working. (Private snapshots also are a must for us, so these two happening at the same time is good!)

**Comment by victorwuky** [comment] 2020-06-06 12:26
All: Thanks for participating in this issue and reporting the problems. We are now working on a fix. In the meantime, the latest release now will surface an error if snapshot creation fails. Previously it was failing silently as noted in this issue. See https://github.com/tilt-dev/tilt/releases/tag/v0.14.2 and https://github.com/tilt-dev/tilt/pull/3400.

We will keep this issue open until there is a full fix for the problem. Thanks!

cc @jazzdan

**Comment by jazzdan** [comment] 2020-06-25 20:32
This should be fixed now!

**Closed by jazzdan** 2020-06-25 20:32 UTC
Labels: bug
