### ISSUE TITLE
Make input debounce timeout configurable

### ISSUE THREAD

**Issue by amoffat-maven** [tilt-dev/tilt#4692] opened 2021-06-25 16:37 UTC
## Describe the Feature You Want
I would like to configure the input debouncing timeout to a custom value, longer than what is currently available.

### Current Behavior
Tilt currently waits a very short time period before triggering a reload after a file changes.

### Why Do You Want This?
A short, non-configurable debounce timeout can result in aggressive reloading if an IDE is resaving a file on (nearly) ever keypress. This results in a very high cpu usage and, I suspect, some weird states where a previous reload has not finished when a new reload request is triggered. If we were able to raise the debounce timeout value to 2-3 seconds (or just allow it to be configured), it would alleviate this issue.

**Additional context**
From a quick search of the code base, this may be the variable that needs to be configurable:

https://github.com/tilt-dev/tilt/blob/59dd5b1b16ad6ffc4113f9c313e85b269448b7a9/web/src/OverviewActionBar.tsx#L464

**Comment by landism** [comment] 2021-06-25 17:48
Thanks for the report!

That sounds pretty annoying!

Some thoughts:
* Saving on every keystroke, even with a debounce, is still going to trigger lots of useless builds that are just going to fail anyway since you're in the middle of editing a file. Just to throw some numbers out there: if your rebuild takes 3 seconds and you type one character per second for ten seconds:
  * without a debounce, you'd trigger builds at t=0,3,6,9,12. With a debounce of 3 seconds, you'd trigger builds at t=3,6,9,12. That's an improvement, but not much of one. (though maybe those numbers aren't a good representation of what you're observing?)
* Do you have a strong preference for saving on every keystroke? Most editors I've seen will auto-save when you tab out. Is that an option in your editor and would you be interested in using it? (sorry, I don't mean to attack the "save-every-character" workflow - I'm just totally unfamiliar with it and mostly downsides are occurring to me, especially when using it with Tilt)
* If you have a strong preference for saving on every keystroke, are you aware of / interested in [`trigger_mode(TRIGGER_MODE_MANUAL)`](https://docs.tilt.dev/api.html#api.trigger_mode)? This will make it so builds only run when you tell them to run, rather than running a bunch of broken builds as you type and your IDE saves mid-line.

**Comment by amoffat-maven** [comment] 2021-06-25 18:22
Thanks for the quick follow @landism !

PyCharm (and I imagine other Intellij IDEs) [seem to be pretty aggressive with auto saving](https://stackoverflow.com/a/28950477), and also make it very difficult to disable. My mention of "every keypress" is probably an exaggeration in retrospect, but it does feel like that sometimes :). There seem to be some workarounds, but I have not tried them yet. The level of effort for these workarounds may be a roadblock to newer devs that Tilt can help alleviate here.

I am using live reloads, so reloading is pretty quick, but I have got the sense that some weird Tilt states that I have gotten in (requiring a `tilt down` + `tilt up`) are a result of live reloading being triggered at bad times.

I wasn't aware of the manual trigger mode! This might be a workaround that gets what I need. I am mainly interested in ensuring that when the Tilt reload triggers, it is >90% likely that I am done typing. As you can imagine, when editing code, there is frequently multi-second pauses as you work through the line. With the low debounce timeout as it is now, and the difficulty in disabling auto-save in Intellij editors, those Tilt reloads are not great. But using a manual mode is pretty good. It does remove the automated-ness of the workflow, but I suppose that that may be better than trying to "guess" the perfect debounce timeout that gets to that >90% guarantee that I mentioned.

I guess we can close this request unless we want to see if others are interested in the feature or have other thoughts?

**Comment by amoffat-maven** [comment] 2021-06-25 18:31
Oh, very cool, the manual trigger mode also plays nice with live reload 👍

**Comment by landism** [comment] 2021-06-28 14:50
> PyCharm (and I imagine other Intellij IDEs) seem to be pretty aggressive with auto saving

Oh, interesting. I primarily use GoLand (another jetbrains IDE) and have not observed this. Thanks for sharing that link. It's good to know there are so many reasons this could happen.

If you want to try out debouncing to see if it is a significant improvement for you, you should be able to do that by prepending a `sleep 3` to all of your builds. For `local_resource`, that's pretty straightforward. For `docker_build`, you'd need to convert to [`custom_build`](https://docs.tilt.dev/custom_build.html#custom-docker-builds) and then prepend the `sleep 3` to the build command. (or if you have a lot of builds, maybe define, e.g., a `debounced_local_resource` function in your Tiltfile that wraps `local_resource` and prepends the sleep).

**Comment by nicks** [comment] 2021-06-29 15:07
is this a duplicate of https://github.com/tilt-dev/tilt/issues/3606 or do you think they're different feature requests?

**Closed** 2021-06-29 15:14 UTC
Labels: enhancement
