### ISSUE TITLE
Continuous `GET /json` to entrypoint. v 0.22.5

### ISSUE THREAD

**Issue by ndrean** [tilt-dev/tilt#4888] opened 2021-08-25 11:02 UTC
### Expected Behavior

I shouldn't have continuous request to an imaginary endpoint '/json' to my entrpoint pod.
### Current Behavior

I have a continuous request `GET /json`in my entrypoint (a Rails pod)
```sh
Started GET "/json" for 127.0.0.1
```
### Steps to Reproduce

1.
2.
3.
4.

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.22.5, built 2021-08-20
System: darwin-amd64
---
Docker (cluster)
- Host: tcp://127.0.0.1:50438
- Server Version: 20.10.7
- API Version: 1.41
- Builder: 2
---
Docker (local)
- Host: [default]
- Server Version: 20.10.7
- Version: 1.41
- Builder: 2
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: test
- Container Runtime: docker
- Version: v1.21.2
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: 57091434cde89fde74ce35d87f653035
- Repo: OchQK9amFYBeE0vL1ij53A==
...
```

#### About Your Use Case

I believe this happened after upgrading to `0.22.5`.

The cluster is running a Rails pod and a Sidekiq pod and Redis and Postgresql. The Rails service is the entrypoint  `kind: NodePort`. The Rails container listens `0.0.0.0`.

**Comment by milas** [comment] 2021-12-09 20:28
Closing as the cause seems to have been from something outside Tilt.

**Closed by milas** 2021-12-09 20:28 UTC
Labels: bug
