### ISSUE TITLE
watcher: no space left on device

### ISSUE THREAD

**Issue by jazzdan** [tilt-dev/tilt#2079] opened 2019-08-20 13:43 UTC
Reported by @arvinderpal [in another thread](https://github.com/windmilleng/tilt/issues/1967#issuecomment-523004200):

>I'm also getting the `Error: notify.Add("/home/awander/go/src/github.com/chuckha/capi-dev/cluster-api"): watcher.Add("/home/awander/go/src/github.com/chuckha/capi-dev/cluster-api/cmd"): no space left on device`
I'm using @chuckha repo as well. 
I'm on Ubuntu 18.04 and have over 300GB free disk space. The error occurs after about 5-6 retries of the `tilt up` command. I tried most of the suggestions here: https://forums.docker.com/t/docker-no-space-left-on-device/69205
The only fix I have is to restart my machine :(

I think this is a file watch leak or something similar, and not related to opaque buildkit build errors.

**Comment by nicks** [comment] 2019-08-20 16:19
fwiw, I ran `tilt up` in this directory and http://localhost:10350/debug/vars shows  watch.naive.numberOfWatches: 885

The "no space left on device" is a common red herring. It doesn't mean that that the system is out of space. It means that the inotify syscall hit a limit, and there's a big in the underlying libraries that erroneously reports the syscall errorcode as an out of disk space error.

**Comment by Arvinderpal** [comment] 2019-08-20 23:28
@jazzdan 
In response to your question in the other thread: 
sudo cat /etc/sysctl.conf | grep "fs.inotify"

I don't see `fs.inotify` in the sysctl.conf

**Comment by Arvinderpal** [comment] 2019-08-20 23:42
I tried the following docker commands as suggested on various posts. None of them fixed the problem though:
``` 
2038  docker system prune -a
2040  docker images purge
2042  docker rmi $(docker images -a -q)
```

**Comment by calvinytong** [comment] 2019-10-10 14:59
We also ran into this and were able to fix it by closing the local text editor (in this case Atom). Once tilt was launched, we could relaunch the text editor and everything seemed to work fine.

**Comment by apolegoshko** [comment] 2020-05-14 19:45
+1 for this issue
![image](https://user-images.githubusercontent.com/19555411/81978653-21527180-962c-11ea-910f-ca0fbf5a020f.png)

**Comment by apolegoshko** [comment] 2020-05-21 17:02
Possible solution of this is increase `/proc/sys/fs/inotify/max_user_watches` parameter. 
I'm using EKS with spot instances workers nodes. Workers nodes uses centos based image.
I've increased `inotify` number using command below:

```bash
$ sudo cat /proc/sys/fs/inotify/max_user_watches
8192
$ sudo sysctl fs.inotify.max_user_watches=524288
$ sudo sysctl -p
$ sudo cat /proc/sys/fs/inotify/max_user_watches
524288
```

So this error related to target environment, not local, and assuming this is not tilt related.

**Comment by KarolisL** [comment] 2020-09-03 11:56
I can confirm what @apolegoshko has found.

In my case, it was JS's `yarn start` which would create a lot of watchers. I have mitigated it with the following init container:
```yaml
      initContainers:
        - name: set-watchers-limit
          image: busybox
          command:
            - sysctl
            - -w
            - fs.inotify.max_user_watches=524288
          securityContext:
            privileged: true
```

**Comment by tvvignesh** [comment] 2020-10-11 18:06
Hi. Had the same issue. Had to increase `/proc/sys/fs/inotify/max_user_watches` as @apolegoshko said and it worked.

**Comment by zulrang** [comment] 2021-08-23 15:24
Why is tilt watching over 8000 files??  Is there a way to exclude directories such as .venvs and node_modules?

**Comment by milas** [comment] 2021-08-30 14:51
@zulrang Are you referring to [tilt-example-nodejs](https://github.com/tilt-dev/tilt-example-nodejs)? What OS are you using? 

In general, I'd recommend reading our guide on file changes which includes guidance around ignores: https://docs.tilt.dev/file_changes.html#where-ignores-come-from

If you believe Tilt is watching files it shouldn't and that guide doesn't help, either reach out in Slack or create a new issue. (This issue is about inotify limits.)

**Comment by lizzthabet** [comment] 2022-04-27 21:27
since this issue was first opened, tilt has shipped a bunch of improvements to file watches! (some of which are outlined in this [blog post](https://blog.tilt.dev/2021/05/07/eyes-on-the-watchers.html). 🗞️ )

i'm going to close this thread now because it's grown to cover several separate issues that have different solutions. if you encounter another file watch bug or have questions, please open a new issue.

**Closed by lizzthabet** 2022-04-27 21:27 UTC
Labels: bug
