### ISSUE TITLE
401 Unauthorized when pulling an image from an authenticated Docker registry

### ISSUE THREAD

**Issue by sssilver** [tilt-dev/tilt#2297] opened 2019-10-03 23:27 UTC
Tilt is failing with 401 Unauthorized when trying to pull an image from an authenticated Docker registry. Running `tilt docker -- pull <image url>` directly works. This caches the image, and subsequent `tilt up`s succeed because they use the cached image.

**Comment by sssilver** [comment] 2019-10-03 23:29
Screenshot:
![image](https://user-images.githubusercontent.com/619878/66170875-9fb55280-e60b-11e9-8a8d-5c5dcb43b4c9.png)

**Comment by sssilver** [comment] 2019-10-04 00:03
After running:

```
$ tilt docker -- pull docker-registry.cfdata.org/stash/cf/cfsetup-images/stretch/master:16-0168a0d7b56d
Running Docker command as:
DOCKER_BUILDKIT=1 docker pull docker-registry.cfdata.org/stash/cf/cfsetup-images/stretch/master:16-0168a0d7b56d
---
16-0168a0d7b56d: Pulling from stash/cf/cfsetup-images/stretch/master
8176e34d5d92: Pull complete 
b99190f16537: Pull complete 
ff5f2c04b21c: Pull complete 
906a3808b97c: Pull complete 
Digest: sha256:f5dbeb24a832cd0b325da12d5325cc76b5a62fa38e0c8aaea80a6ab547aac28c
Status: Downloaded newer image for docker-registry.cfdata.org/stash/cf/cfsetup-images/stretch/master:16-0168a0d7b56d
docker-registry.cfdata.org/stash/cf/cfsetup-images/stretch/master:16-0168a0d7b56d
```
everything comes up.

**Comment by nicks** [comment] 2019-10-04 15:38
Oof, sorry to hear about this. 

I tried to reproduce this with both a gcr.io private registry and a hub.docker.com private registry, and both worked ok for me. Do you know what docker-registry.cfdata.org uses for auth?

**Comment by sssilver** [comment] 2019-10-04 19:36
It's https://github.com/cesanta/docker_auth

**Comment by jazzdan** [comment] 2019-10-08 19:58
@sssilver I've tried to reproduce with [this example repo](https://github.com/windmilleng/docker_auth_test).

Do you know what credential helper you have configured for `docker-registry.cfdata.org`? (You can see the mapping of registry to credential helper in `~/.docker/config.json`)

Something we thought of is that maybe there's a token that is expiring while Tilt is running. Does Tilt ever successfully pull down the image, even when you just start up Tilt?

Also, can you take a look in `env` for these environment variables? https://docs.docker.com/engine/reference/commandline/cli/ Do you have any of them set?

**Comment by jazzdan** [comment] 2019-10-08 20:00
Also, what's your output for `tilt doctor`?

If you think it would be more helpful I'm also happy to jump on a call to help resolve this (dmiller@tilt.dev is my email address).

**Comment by jazzdan** [comment] 2019-10-22 14:51
Hey @sssilver just checking in to see if this is still a problem for you!

**Comment by nicks** [comment] 2019-12-02 16:18
Since we haven't heard any other reports of this, and haven't been able to repro with known authenticated registries, I'm going to move this ticket to low-priority. We can raise the priority again if we get more info

**Comment by lizzthabet** [comment] 2022-04-21 20:49
echoing what @nicks said above: we haven't gotten any more reports, so i'm going to close this issue for now.

**Closed by lizzthabet** 2022-04-21 20:49 UTC
Labels: bug
