### ISSUE TITLE
After updating a source file and syncing, file watcher is triggered twice

### ISSUE THREAD

**Issue by rhyek** [tilt-dev/tilt#4369] opened 2021-03-26 05:30 UTC
### Expected Behavior
After updating a source file and tilt syncs that file, `tsc --watch` should be triggered only once.

### Current Behavior
It is being triggered twice.

### Steps to Reproduce
- have this Tiltfile
```
docker_build('restaurant-utils/api', '.',
  dockerfile='apps/api/Dockerfile.dev',
  only=[
    './pnpm-lock.yaml',
    './pnpm-workspace.yaml',
    './tsconfig.json',
    './apps/api'
  ],
  live_update=[
    sync('./pnpm-lock.yaml', '/monorepo/'),
    sync('./pnpm-workspace.yaml', '/monorepo/'),
    sync('./tsconfig.json', '/monorepo/'),
    sync('./apps/api', '/monorepo/apps/api'),
    run('pnpm i --frozen-lockfile', trigger=['./pnpm-lock.yaml', './apps/api/package.json'])
  ]
)
k8s_yaml('apps/api/k8s.yaml')

k8s_resource('api', port_forwards=3000)
```
- have this structure (this is a private repo)

![image](https://user-images.githubusercontent.com/702922/112585951-76205600-8dc0-11eb-88ec-f97d7cfbd7e7.png)

- modify `apps/api/src/app.service.ts` on the host file system and get this:

![image](https://user-images.githubusercontent.com/702922/112586035-a7008b00-8dc0-11eb-898d-159e49a7819b.png)

- `touch` the same file from within the container and get this (`tsc --watch` is triggered only once correctly):

![image](https://user-images.githubusercontent.com/702922/112586215-fcd53300-8dc0-11eb-8921-29f4d7097be6.png)

#### `tilt doctor` Output

```
❯ tilt doctor
Tilt: v0.19.0, built 2021-03-19
System: linux-amd64
---
Docker
- Host: [default]
- Version: 1.41
- Builder: 2
---
Kubernetes
- Env: kind-0.6+
- Context: kind-restaurant-utils
- Cluster Name: kind-restaurant-utils
- Namespace: default
- Container Runtime: containerd
- Version: v1.20.2
- Cluster Local Registry: {Host:localhost:34081 hostFromCluster: SingleName:}
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: f4dd7fbe521225d80011e5a737762522
- Repo: 
```

#### More info
- this is the output of `inotifywait -mr .` when modifying the file on the host
```
./src/ DELETE app.service.ts
./src/ CREATE app.service.ts
./src/ OPEN app.service.ts
./src/ MODIFY app.service.ts
./src/ CLOSE_WRITE,CLOSE app.service.ts
./src/ ATTRIB app.service.ts
./src/ OPEN app.controller.ts
./src/ ACCESS app.controller.ts
./src/ CLOSE_NOWRITE,CLOSE app.controller.ts
./src/ OPEN app.service.ts
./src/ ACCESS app.service.ts
./src/ CLOSE_NOWRITE,CLOSE app.service.ts
./src/ OPEN app.module.ts
./src/ ACCESS app.module.ts
./src/ CLOSE_NOWRITE,CLOSE app.module.ts
./src/ OPEN main.ts
./src/ ACCESS main.ts
./src/ CLOSE_NOWRITE,CLOSE main.ts
./node_modules/ OPEN,ISDIR @types
./node_modules/@types/ OPEN,ISDIR 
./node_modules/ ACCESS,ISDIR @types
./node_modules/@types/ ACCESS,ISDIR 
./node_modules/ ACCESS,ISDIR @types
./node_modules/@types/ ACCESS,ISDIR 
./node_modules/ CLOSE_NOWRITE,CLOSE,ISDIR @types
./node_modules/@types/ CLOSE_NOWRITE,CLOSE,ISDIR 
./dist/ MODIFY app.service.js.map
./dist/ OPEN app.service.js.map
./dist/ MODIFY app.service.js.map
./dist/ CLOSE_WRITE,CLOSE app.service.js.map
./dist/ MODIFY app.service.js
./dist/ OPEN app.service.js
./dist/ MODIFY app.service.js
./dist/ CLOSE_WRITE,CLOSE app.service.js
./dist/ MODIFY app.service.d.ts.map
./dist/ OPEN app.service.d.ts.map
./dist/ MODIFY app.service.d.ts.map
./dist/ CLOSE_WRITE,CLOSE app.service.d.ts.map
./dist/ OPEN app.service.d.ts
./dist/ ACCESS app.service.d.ts
./dist/ CLOSE_NOWRITE,CLOSE app.service.d.ts
./dist/ MODIFY app.service.d.ts
./dist/ OPEN app.service.d.ts
./dist/ MODIFY app.service.d.ts
./dist/ CLOSE_WRITE,CLOSE app.service.d.ts
./dist/ MODIFY tsconfig.build.tsbuildinfo
./dist/ OPEN tsconfig.build.tsbuildinfo
./dist/ MODIFY tsconfig.build.tsbuildinfo
./dist/ CLOSE_WRITE,CLOSE tsconfig.build.tsbuildinfo
./dist/ ATTRIB app.controller.js
./dist/ ATTRIB app.controller.js.map
./dist/ ATTRIB app.controller.d.ts
./dist/ ATTRIB app.controller.d.ts.map
./dist/ ATTRIB app.module.js
./dist/ ATTRIB app.module.js.map
./dist/ ATTRIB app.module.d.ts
./dist/ ATTRIB app.module.d.ts.map
./dist/ ATTRIB main.js
./dist/ ATTRIB main.js.map
./dist/ ATTRIB main.d.ts
./dist/ ATTRIB main.d.ts.map
./ OPEN,ISDIR src
./src/ OPEN,ISDIR 
./ ACCESS,ISDIR src
./src/ ACCESS,ISDIR 
./ ACCESS,ISDIR src
./src/ ACCESS,ISDIR 
./ CLOSE_NOWRITE,CLOSE,ISDIR src
./src/ CLOSE_NOWRITE,CLOSE,ISDIR 
./ OPEN package.json
./ ACCESS package.json
./ CLOSE_NOWRITE,CLOSE package.json
./dist/ OPEN main.js
./dist/ ACCESS main.js
./dist/ CLOSE_NOWRITE,CLOSE main.js
./ OPEN,ISDIR 
./ ACCESS,ISDIR 
./ ACCESS,ISDIR 
./ CLOSE_NOWRITE,CLOSE,ISDIR 
./ OPEN,ISDIR src
./src/ OPEN,ISDIR 
./ ACCESS,ISDIR src
./src/ ACCESS,ISDIR 
./ ACCESS,ISDIR src
./src/ ACCESS,ISDIR 
./ CLOSE_NOWRITE,CLOSE,ISDIR src
./src/ CLOSE_NOWRITE,CLOSE,ISDIR 
./ OPEN package.json
./ ACCESS package.json
./ CLOSE_NOWRITE,CLOSE package.json
./dist/ OPEN main.js
./dist/ ACCESS main.js
./dist/ CLOSE_NOWRITE,CLOSE main.js
./dist/ OPEN app.module.js
./dist/ ACCESS app.module.js
./dist/ CLOSE_NOWRITE,CLOSE app.module.js
./dist/ OPEN app.controller.js
./dist/ ACCESS app.controller.js
./dist/ CLOSE_NOWRITE,CLOSE app.controller.js
./dist/ OPEN app.service.js
./dist/ ACCESS app.service.js
./dist/ CLOSE_NOWRITE,CLOSE app.service.js
```
- this is using the `touch` from within the container:
```
./src/ ATTRIB app.service.ts
./src/ OPEN app.controller.ts
./src/ ACCESS app.controller.ts
./src/ CLOSE_NOWRITE,CLOSE app.controller.ts
./src/ OPEN app.service.ts
./src/ ACCESS app.service.ts
./src/ CLOSE_NOWRITE,CLOSE app.service.ts
./src/ OPEN app.module.ts
./src/ ACCESS app.module.ts
./src/ CLOSE_NOWRITE,CLOSE app.module.ts
./src/ OPEN main.ts
./src/ ACCESS main.ts
./src/ CLOSE_NOWRITE,CLOSE main.ts
./node_modules/ OPEN,ISDIR @types
./node_modules/@types/ OPEN,ISDIR 
./node_modules/ ACCESS,ISDIR @types
./node_modules/@types/ ACCESS,ISDIR 
./node_modules/ ACCESS,ISDIR @types
./node_modules/@types/ ACCESS,ISDIR 
./node_modules/ CLOSE_NOWRITE,CLOSE,ISDIR @types
./node_modules/@types/ CLOSE_NOWRITE,CLOSE,ISDIR 
./dist/ ATTRIB app.controller.js
./dist/ ATTRIB app.controller.js.map
./dist/ ATTRIB app.controller.d.ts
./dist/ ATTRIB app.controller.d.ts.map
./dist/ ATTRIB app.module.js
./dist/ ATTRIB app.module.js.map
./dist/ ATTRIB app.module.d.ts
./dist/ ATTRIB app.module.d.ts.map
./dist/ ATTRIB app.service.js
./dist/ ATTRIB app.service.js.map
./dist/ ATTRIB app.service.d.ts
./dist/ ATTRIB app.service.d.ts.map
./dist/ ATTRIB main.js
./dist/ ATTRIB main.js.map
./dist/ ATTRIB main.d.ts
./dist/ ATTRIB main.d.ts.map
./dist/ ATTRIB tsconfig.build.tsbuildinfo
./ OPEN package.json
./ ACCESS package.json
./ CLOSE_NOWRITE,CLOSE package.json
./dist/ OPEN main.js
./dist/ ACCESS main.js
./dist/ CLOSE_NOWRITE,CLOSE main.js
./dist/ OPEN app.module.js
./dist/ ACCESS app.module.js
./dist/ CLOSE_NOWRITE,CLOSE app.module.js
./dist/ OPEN app.controller.js
./dist/ ACCESS app.controller.js
./dist/ CLOSE_NOWRITE,CLOSE app.controller.js
./dist/ OPEN app.service.js
./dist/ ACCESS app.service.js
./dist/ CLOSE_NOWRITE,CLOSE app.service.js
```

**Comment by nicks** [comment] 2021-03-26 15:05
Thanks for the detailed report! Trying to repro now.

What do you see if you use `kubectl cp` to copy the file into the container - one file watcher trigger or two?

**Comment by nicks** [comment] 2021-03-26 20:11
Hmmm...I spent some time investigating this, and was not able to reproduce this problem. 

Let me share a bit of what I learned though:

- Here's the test harness that I used to try to repro: https://github.com/tilt-dev/tilt-frontend-demo/tree/nicks/issue4369. I edited index.tsx and only saw one recompile.

Can you try that to see if you also get duplicate recompiles? That would help us determine if the difference is something on your machine, or something in your project.

- The inotify events you shared are about what I would expect to happen. I would not expect them to trigger duplicate tsc recompiles. (we could have a long walkthrough on why those inotify events are expected, but I'm not sure that would get us any closer to diagnosing the problem here.)

- what version of tsc are you using? I tested with 4.2.3. The docs say they made major changes to their watch mechanism in 3.8, so that could cause differences here.

- how does your tsconfig.json specify files watched and watch settings? I could imagine minor differences here causing major changes to the watch strategy that tsc is using, which might behave differently inside a container.

**Comment by nicks** [comment] 2021-03-26 20:12
also, to understand the priority of this - does duplicate recompilation cause any real usability issue? i would have assumed it's basically cosmetic (and only is a problem if you're worried about log spam)

**Comment by rhyek** [comment] 2021-03-26 20:38
Hi, sorry for answering late. With `kubectl cp apps/api/src/app.service.ts api-bd78b6645-fgrk7:/monorepo/apps/api/src/app.service.ts` I still get the 2 reloads.

`tsc` version is 4.2.3. Regarding watch options I had tried setting both `watchFile` and `watchDirectory` to `fixedPollingInterval` with the same results.

But having done the `kubectl cp` and seeing the same results does indeed confirm this is not a `tilt` issue. Thank you for your investigations! :-)

I'll try and look further into this later today and report back if I find anything.

**Comment by milas** [comment] 2021-12-10 16:08
Closing this as it appears to not be a Tilt issue since the same behavior occurs with `kubectl cp`.

**Closed by milas** 2021-12-10 16:08 UTC
Labels: bug
