### ISSUE TITLE
Emacs autosave causes Tilt reload

### ISSUE THREAD

**Issue by rome-user** [tilt-dev/tilt#6187] opened 2023-08-02 00:24 UTC
Hi,

I have autosave files configured in Emacs like so.
```elisp
(setq backup-by-copying   t
      version-control     t
      delete-old-versions t
      kept-new-versions   6
      kept-old-versions   2)
```

When I decide to edit a file, but not save it, Tilt will automatically refresh because Emacs creates a tempfile prefixed with `.#`. For instance, if I am editing `foobar`, then `.#foobar` is created, and Tilt decides to rebuild.

According to the documentation, "Tilt has a hard-coded list of temp files in common text editors (Emacs, Vim, etc.)." But this does not seem to be the case for Emacs.

**Comment by nicks** [comment] 2023-08-02 22:40
Hmmm...thanks for reporting, but I wasn't able to reproduce this problem. Here's what I tried:

1. Checkout out the example project - https://github.com/tilt-dev/tilt-example-html/tree/master/0-base
2. Ran `tilt up`
3. Ran `touch .#foobar`
4. Confirmed that no rebuilds were triggered

we also have fairly good unit tests for this, see
https://github.com/tilt-dev/tilt/blob/master/internal/ignore/path_matcher_test.go#L112

what am i missing?

**Comment by nicks** [comment] 2023-09-01 17:21
closing this since we're not able to repro

**Closed by nicks** 2023-09-01 17:21 UTC
Labels: needs repro case
