### ISSUE TITLE
Pin Icon by resource is wrapping incorrectly when scroll bars set to Always show on macOS

### ISSUE THREAD

**Issue by taylorcoffelt** [tilt-dev/tilt#3903] opened 2020-11-05 20:40 UTC
### Expected Behavior
Pin Icon stays inline with each resource in Web UI

### Current Behavior
When Resource Items + Pinned Resources are longer than the list container height, the pin icons are no longer inline. This appears to be due to scrollbar width on the container.

### Steps to Reproduce
0. Use macOS. Set `Show scroll bars` to `Always`.
1. `tilt up` with a fair amount of resources
2. In the WebUI, pin several items until the list is longer than the resource container and scrollbars are shown
3. Observe that overflow causes the resource block and pin to wrap

<img width="682" alt="Screen Shot 2020-11-05 at 4 41 36 PM" src="https://user-images.githubusercontent.com/10860550/98299541-dafc2080-1f85-11eb-8a20-70e0f32f2757.png">

Firefox:
![image](https://user-images.githubusercontent.com/690213/98293720-070aa800-1f6c-11eb-96dd-b09f985372ef.png)

Chrome:
![image](https://user-images.githubusercontent.com/690213/98293779-1be73b80-1f6c-11eb-8a4d-9a97b2eff60b.png)

#### `tilt doctor` Output
```
$ tilt doctor
Tilt: v0.17.10, built 2020-10-30
System: darwin-amd64
...
```

#### About Your Use Case
It's harder to interact with pinned resources when the pins are on separate lines

**Comment by victorwuky** [comment] 2020-11-05 20:54
Thanks @taylorcoffelt. That's really weird. I'm not able to reproduce it. This is what I see:

![2020-11-05 15 49 28](https://user-images.githubusercontent.com/10860550/98294980-cbc5a480-1f7e-11eb-8a95-2d36bd218629.gif)

Do you mind taking a few more screenshots / gifs showing more context and I'll try to reproduce?

**Comment by taylorcoffelt** [comment] 2020-11-05 21:06
@victorwuky I'll work on getting a more reproducible context/Tiltfile for you
Just a hunch from the gif you sent vs my environment though, none of your resource names are long enough to trigger the name truncation (ellipses) that I have on some of my resources, that may be a factor.

**Comment by taylorcoffelt** [comment] 2020-11-05 21:08
And that's negative, shortening the names doesn't fix the issue for me.

**Comment by taylorcoffelt** [comment] 2020-11-05 21:15
Here is a GIF of the issue happening when I pin resources:
![Nov-05-2020 14-13-04](https://user-images.githubusercontent.com/690213/98297059-18a27e80-1f71-11eb-879f-1cd355f56ec1.gif)

**Comment by taylorcoffelt** [comment] 2020-11-05 21:22
Ok, I think this is specific to macOS and the way that scrollbars are handled via overlay vs just inserting them into the DOM layout.
Toggling this option from 'Always' to 'When Scrolling' changes the scrollbars from having their own 'tray' to an overlay on the container, and the Resources all fit on one line again.

![image](https://user-images.githubusercontent.com/690213/98297738-17be1c80-1f72-11eb-88dc-4736b6da6754.png)

**Comment by taylorcoffelt** [comment] 2020-11-05 21:24
![Nov-05-2020 14-23-42](https://user-images.githubusercontent.com/690213/98298040-987d1880-1f72-11eb-8e58-5c9405336776.gif)

**Comment by victorwuky** [comment] 2020-11-05 21:38
Ah thanks @taylorcoffelt . I'm able to reproduce when I've selected `Always`, like you said.

<img width="342" alt="Screen Shot 2020-11-05 at 4 34 34 PM" src="https://user-images.githubusercontent.com/10860550/98298960-e4d15400-1f84-11eb-8dc7-8a6bc2cb1a51.png">

@landism : Do let us know if this can be fixed. (I'm not aware lots of people use `Always` as a setting. But at least Taylor here does!)

**Comment by landism** [comment] 2020-11-06 16:13
> Do let us know if this can be fixed. (I'm not aware lots of people use Always as a setting. But at least Taylor here does!)

Yeah, Han and I noticed some weirdness with this when we were trying to tweak the behavior and I think this will be fixed by upcoming changes.

**Comment by victorwuky** [comment] 2020-11-06 16:29
Cool thanks @landism . I'll follow along and keep testing this with each subsequent Tilt release.

**Closed** 2020-11-13 20:39 UTC
Labels: bug
