### ISSUE TITLE
Rebuilds with Live Update: Nested file deps

### ISSUE THREAD

**Issue by maximegel** [tilt-dev/tilt#5372] opened 2022-01-12 01:04 UTC
### Expected Behavior
Nested file deps should trigger live updates.

### Current Behavior
Specifying nested files as ressource dependency using `local_resource()` `deps` param or using `sync()` do not trigger a rebuild.

### Steps to Reproduce

1. Add a `local_resource()` in Tiltfile:
```starlark
local_resource(
    name = "watch",
    cmd = "cat apps/foo.txt",
    deps = ["./apps/foo.txt"],
)
```
2. Edit "./apps/foo.txt"
3. Nothing happens

It works fine if a move "./apps/foo.txt" in the Tiltfile directory and update the path in Tiltfile.

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.23.5, built 2022-01-07
System: linux-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.11+azure-3
- API Version: 1.41
- Builder: 2
- Compose Version: v1.29.2 (build 5becea4c)
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: containerd
- Version: v1.22.3
- Cluster Local Registry: {Host:localhost:5000 hostFromCluster: SingleName:}
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: d77c3200d1ed9b89b88c2c6c06f96bfc
- Repo: n2qHgzbOabs4cpiCWSL7kA==
```

#### About Your Use Case

I just started working with Tilt maybe I'm doing something wrong?

**Comment by lianmakesthings** [comment] 2022-01-12 14:52
Hi @maximegel,
Tilt _should_ be able to handle all file dependencies as long as you provide the correct file path.
I tried this on my local machine and unfortunately wasn't able to reproduce your issue. 
![Screen Recording 2022-01-12 at 15 09 22 mov](https://user-images.githubusercontent.com/2743542/149163509-b8d8bfc4-02e1-4f37-8510-68f70f1d1e7d.gif)

This is a bit of a basic question, but are you sure you saved the file after editing it?

**Comment by maximegel** [comment] 2022-01-13 14:36
Hi @lianmakesthings, yes I saved the file properly. I'm working inside a ubuntu devcontainer and I installed Tilt by downloading and unpacking the release artifact from github. Do it need additionnal ubuntu packages?

**Comment by lianmakesthings** [comment] 2022-01-13 15:47
Hi @maximegel, could you elaborate a bit more on how your setup works?
I understand you run a container with Ubuntu and run Tilt inside that. Do you edit files on your host machine that is mounted into that container, or do they live only in there?

**Comment by nicks** [comment] 2022-01-13 15:50
this is a long shot, but any chance you're running Ubuntu on Windows/WSL2 and have a filesystem that's crossing windows/linux boundaries (e.g., some parts of the directory tree are managed by Windows and some by Linux).

Tilt will generally work on WSL, but there are some nuances if you're running Ubuntu on a filesystem controlled by Windows, and which might behave this way:
https://github.com/microsoft/WSL/issues/4739
https://github.com/tilt-dev/tilt/issues/3101

**Comment by maximegel** [comment] 2022-01-13 21:48
I'm [developing inside a devcontainer](https://code.visualstudio.com/docs/remote/containers) which I access using the Visual Studio Code Remote - Containers extension. So yes, the files are mounted from Windows into a Ubuntu container via a Docker volume.

**Comment by lianmakesthings** [comment] 2022-01-14 12:41
@maximegel Are you running Ubuntu on WSL2 and could it be related to the issue @nicks linked?
https://github.com/microsoft/WSL/issues/4739

**Comment by nicks** [comment] 2022-01-28 23:21
marking this as a duplicate of the WSL issue, which has some good workarounds that should help!

**Closed by nicks** 2022-01-28 23:21 UTC
Labels: bug
