### ISSUE TITLE
When using custom extensions repos the language server report extension cannot be found

### ISSUE THREAD

**Issue by gayanper** [tilt-dev/tilt#6407] opened 2024-07-01 18:49 UTC
### Current Behavior
When loading extensions from a custom repo as defined in https://docs.tilt.dev/extensions#managing-your-own-extension-repo The Language server shows diagnostics error in the Tiltfile with the message "loading extension <name>: no extension tiltfile found at /Users/<user>/Library/Application Support/tilt-dev/tilt_modules/github.com/tilt-dev/tilt-extensions/<name>/Tiltfile"

It seems the LS is looking at wrong directory.

### Steps to Reproduce
1. Create a custom Tilt extension in a GitHub repository
2. Load it as defined in https://docs.tilt.dev/extensions#managing-your-own-extension-repo 

#### `tilt doctor` Output
```
Tilt: v0.33.17, built 2024-06-12
System: darwin-arm64
---
Docker
- Host: unix:///Users/<user>/.docker/run/docker.sock
- Server Version: 26.1.1
- API Version: 1.45
- Builder: 2
- Compose Version: v2.27.0-desktop.2
---
Kubernetes
- Env: docker-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: data-next
- Container Runtime: docker
- Version: v1.29.2
- Cluster Local Registry: none
---
```

#### About Your Use Case
My use case is I´m trying to define some custom functions specific for my organisation use cases so that we can share them as a extension to be used in Tilt files throughout the organisation without duplicating those functions in each tilt file.

**Comment by nicksieger** [comment] 2024-07-01 18:58
I think Tilt should work fine, it's just that you see that error in VS code right? Please correct me if I misunderstand the situation. 

I think this is a duplicate of tilt-dev/vscode-tilt#30.

**Comment by gayanper** [comment] 2024-07-01 19:10
Yes Tilt works correctly. Its the language server who interprets this wrong.

**Closed** 2024-07-01 20:22 UTC
Labels: bug, duplicate
