### ISSUE TITLE
Server Pending State when deploying istio-base

### ISSUE THREAD

**Issue by emanuele-leopardi** [tilt-dev/tilt#6292] opened 2024-01-09 14:39 UTC
To install istio it's possible to issue the following code:
```
  helm_repo('istio', 'https://istio-release.storage.googleapis.com/charts',labels=["repo"])
  namespace_create("istio-system",allow_duplicates=True)

  helm_resource(
    'istio-base',
    'istio/base',
    labels="istio",
    resource_deps=['istio'],
    namespace="istio-system",
    flags=[
    '--set', 'defaultRevision=default'
    ]
  )
```
Base chart contains only CRD of Istio used by other istio components helm charts  (irrelevant to this issue) 

The problem is that Tilt seems to wait for the readiness state of the installation ( maybe a pod or something similar) but there is none. So it shows no particular readiness check and keeps hanging.

### Steps to Reproduce

1. Apply the above code
2.
3.
4.

#### `tilt doctor` Output

```
$ tilt doctor
...

Tilt: v0.30.5, built 2022-07-14
System: linux-amd64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 24.0.6
- API Version: 1.43
- Builder: 2
- Compose Version: v2.21.0
---
Kubernetes
- Env: kind
- Context: kind-istio-testing
- Cluster Name: kind-istio-testing
- Namespace: default
- Container Runtime: containerd
- Version: v1.27.3
- Cluster Local Registry: none


The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: 45763c2370f498cd0b06f69a48ecf68f
- Repo: 0LVXHf4gq2LU6mYKzOC0dQ==

```

**Comment by nicks** [comment] 2024-01-09 14:55
thanks for the report! marking as a duplicate of https://github.com/tilt-dev/tilt/issues/6058

**Closed by nicks** 2024-01-09 14:55 UTC
Labels: bug
