### ISSUE TITLE
Provide a way to trigger/reload the main Tiltfile from the browser

### ISSUE THREAD

**Issue by KOGI** [tilt-dev/tilt#3662] opened 2020-08-04 20:27 UTC
All other resources in the browser can be manually re-run with the ![image](https://user-images.githubusercontent.com/1231996/89341475-3bfa1c80-d656-11ea-804c-60459038c517.png) icon

It would be very helpful if we could do the same for the main Tiltfile, too

**Comment by nicks** [comment] 2020-08-05 16:32
I think this is a duplicate of https://github.com/tilt-dev/tilt/issues/2957 ?

**Comment by jazzdan** [comment] 2020-08-05 16:39
Yup, good call @nicks

**Closed by jazzdan** 2020-08-05 16:39 UTC
Labels: enhancement
