### ISSUE TITLE
webdev-port conflicts not being detected on macos

### ISSUE THREAD

**Issue by landism** [tilt-dev/tilt#4281] opened 2021-03-08 17:06 UTC
### Steps to Reproduce
1. on macos: with a dev build of tilt, run tilt up
2. in another window, with the same dev build, run tilt up --port 10351
note:  I haven't tested this on linux. There have been a few issues in the past with this behavior differing between macos and linux.

### Expected Behavior
some kind of error because both processes are trying to run yarn on the same port

### Current Behavior
no error, and the second tilt talks to the first tilt's yarn
the second yarn outputs this (note: this output is hidden by default and I had to modify tilt to log it):
```
Something is already running on port 46764. Probably:
  /usr/local/Cellar/node@12/12.18.1/bin/node /Users/matt/go/src/github.com/tilt-dev/tilt/web/node_modules/react-scripts/scripts/start.js (pid 33948)
  in /Users/matt/go/src/github.com/tilt-dev/tilt/web

Would you like to run the app on another port instead? › (Y/n)
```
and then sits there forever (which seems like it'd be a nice feature for Tilt!)
I don't know if that behavior changed recently. I think the main issue is that our [port check](https://github.com/tilt-dev/tilt/blob/56d2bdbb21ab365250ce82130d30b6484b09ffdd/pkg/assets/dev.go#L149-L148) is unexpectedly returning a nil error when the port is already in use.

#### About Your Use Case
This is definitely messy and seems like it has the potential to be a problem. However, I'm not actually sure if this is a problem in practice! In theory they're both running yarn servers serving code from the same dir, so it doesn't matter. I've actually wanted a persistent yarn server that's independent of tilt so that I wouldn't have to go through the 30 seconds of waiting for yarn to spin up on `tilt up`, and this gives me a terrible way to get one. If someone is running multiple dev builds of tilt that were built in different directories, that could manifiest a problem.

**Comment by milas** [comment] 2021-03-19 15:28
This could be "fixed" to error out from Webpack by just not attaching `stdin` to the process -- it thinks it's running in interactive mode so pops that prompt vs just erroring out: https://github.com/tilt-dev/tilt/blob/e6ffd5c669fd22c6a49c44625710d3d05003020d/pkg/assets/dev.go#L122-L124

That said, attaching fake input was done in #3388 to fix an issue, so either Webpack/CRA have flip-flopped behaviors (not unlikely) and/or there's OS differences (also not unlikely).

With that removed, Webpack still works for me on macOS and a second instance errors out:
```
$ go run ./cmd/tilt up -f ./web/storybook.tiltfile --port 10351
Tilt started on http://localhost:10351/
v0.18.13-dev, built 2021-03-19

(space) to open the browser
(s) to stream logs (--stream=true)
(t) to open legacy terminal mode (--legacy=true)
(ctrl-c) to exit
Error: Tilt dev server stopped unexpectedly
Stdout:
yarn run v1.22.10
$ react-scripts start
Something is already running on port 46764.
Done in 2.46s.

Stderr:


exit status 1
```

Unfortunately on the CRA side, they determine interactive to just be if they think they have a TTY attached, there's no ability to override with a `NON_INTERACTIVE` env var or something: https://github.com/facebook/create-react-app/blob/5fc8350c89ff730cdfd067bbd86a90dab393d21b/packages/react-dev-utils/WebpackDevServerUtils.js#L23

But the root cause of the port checker is just IPv4/IPv6 fun, so one-line fix is in #4344.

**Closed** 2021-03-22 20:18 UTC
Labels: bug
