### ISSUE TITLE
Tilt is not respecting .dockerignore during image building

### ISSUE THREAD

**Issue by kklimonda-fn** [tilt-dev/tilt#6113] opened 2023-05-08 12:04 UTC
### Expected Behavior
`docker_build` should respect what's in `.dockerignore` and not copy extraneous files. This seems like a regression as the same bug has been reported previously as https://github.com/tilt-dev/tilt/issues/5745 and closed by https://github.com/tilt-dev/tilt/pull/5768.

### Current Behavior
Even though `.dockerignore` is ignoring `node_modules/` and its subdirectories, Tilt is still copying everything as part of the image building:

```
     Building image
     resolve image config for docker.io/docker/dockerfile:1 [done: 3.692s]
     docker-image://docker.io/docker/dockerfile:1@sha256:39b85bbfa7536a5feceb7372a0817649ecb2724562a38360f4d6a7782a409b14
     [base 1/3] FROM docker.io/library/node:19.0.0-alpine@sha256:1a04e2ec39cc0c3a9657c1d6f8291ea2f5ccadf6ef4521dec946e522833e87ea
     [background] read source files 226.82MB [done: 1m55.466s]
[...]
```

### Steps to Reproduce

I'm assuming the repository from the previous ticket should still help with reproduction.

#### System Setup
I'm running docker builder on a separate host and exporting the following variables so that image building is done remotely:
```
~ > env |grep DOCKER_
DOCKER_BUILDKIT=1
DOCKER_HOST=ssh://kklimonda@[worker]
~ >


#### `tilt doctor` Output
<!--- Run `tilt doctor` and paste the output here so we know about your environment -->
```
~ > tilt doctor
Tilt: v0.32.3, built 2023-04-28
System: darwin-arm64
---
Docker
- Host: http://docker.example.com
- Server Version: 23.0.3
- API Version: 1.42
- Builder: 2
- Compose Version: v2.6.1
---
Kubernetes
- Env: gke
- Context: gke_devel-309501_us-central1_kklimonda-dev-cluster
- Cluster Name: gke_devel-309501_us-central1_kklimonda-dev-cluster
- Namespace: default
- Container Runtime: containerd
- Version: v1.25.8-gke.500
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: e1bab5077955fa3d0b30ab34d5dabd67
- Repo: AAbrH3ndj1GFs9Ql+ZkkqQ==
~ >
```

#### About Your Use Case
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

**Comment by nicks** [comment] 2023-05-08 13:23
thanks for the report! I was not able to reproduce this problem. I tried to repro by:
1) https://github.com/tilt-dev/tilt/tree/master/integration/ignores
2) running `tilt up`
3) Putting large files in the dirs covered by .dockerignore and confirming they were ignored.
Can you post repro steps of the problems you're having?

**Comment by nicks** [comment] 2023-06-02 20:05
closing this, since there's not enough information here to take action. happy to reopen if you have repro steps.

**Closed by nicks** 2023-06-02 20:05 UTC
Labels: bug, needs repro case
