### ISSUE TITLE
Support additional contexts in docker_build

### ISSUE THREAD

**Issue by Yeep** [tilt-dev/tilt#6162] opened 2023-07-06 13:41 UTC
## Describe the Feature You Want
It is now possible to override contexts inside a Dockerfile with additional build contexts specified on the command line. See https://www.docker.com/blog/dockerfiles-now-support-multiple-build-contexts/. It would be great if we could do this from Tilt without having to use `custom_build` to call out to the docker cli. Alternatively it would be nice if the `docker_build` command at least exposed a deps array so that files from additional contexts can be synchronised with live update.

### Current Behavior
`docker_build` only accepts a single, unnamed context.
If `docker_build` depends on an image with multiple contexts built with `custom_build`, it is not possible to sync files from the additional contexts because they aren't in the image's deps list.

### Why Do You Want This?
I have a complex dependency tree of docker builds defined in a docker-bake.hcl file including a number of nodejs projects that use Docker additional contexts to pull in common libraries and certificates. I am calling out to `docker buildx bake` using `custom_build` to build images then using the method from the `docker_build_sub` plugin to replace the entrypoint.

With Tilt as it is now I am able to live update files from the main application context but not from any shared libraries.

**Additional context**
Native support for docker bake files would be even better but I understand that's likely much more complicated.

**Comment by nicks** [comment] 2023-07-07 16:20
thanks for the report! I'm going to mark this as a duplicate of https://github.com/tilt-dev/tilt/issues/5943

**Closed by nicks** 2023-07-07 16:20 UTC
Labels: enhancement
