### ISSUE TITLE
Docker Compose v2 with compose dependencies cannot be brought up

### ISSUE THREAD

**Issue by nicksieger** [tilt-dev/tilt#5829] opened 2022-05-20 16:09 UTC
### Expected Behavior
I can declare dependencies between services in my compose file and Tilt will bring them all up

### Current Behavior
In some cases, services with dependencies fail to be brought up and print an error message `no such service: dependent-service`

### Steps to Reproduce
1. Make sure `docker-compose version` returns version 2.5 or higher (or `docker compose version` after #5825 is released)
2. Run `tilt up` with https://github.com/tilt-dev/tilt-example-docker-compose
3. See the error message `no such service: redis`

### Context
- Related compose issue: docker/compose#9427
- Current workaround is to comment or remove dependencies in your compose file like `depends_on` or `links` and instead declare dependencies with Tilt using `dc_resource(..., resource_deps=[...])`

**Comment by boxmein** [comment] 2022-08-01 21:09
This is affecting us with docker compose 2.6.1 tilt 0.30.5

**Comment by nicksieger** [comment] 2022-08-02 17:45
@boxmein does it look anything like docker/compose#9591? There still might be an issue with dependencies.

**Comment by boxmein** [comment] 2022-08-24 10:36
> @boxmein does it look anything like [docker/compose#9591](https://github.com/docker/compose/issues/9591)? There still might be an issue with dependencies.

Yes, it looks to be caused by that issue! I will have to check if it's been resolved with the latest version.

**Comment by ShadowLNC** [comment] 2022-09-06 23:58
Just want to confirm that Docker Desktop 4.12 was released on Friday and appears to have resolved it for me with our custom compose file

**Closed** 2022-09-07 15:46 UTC
Labels: bug
