### ISSUE TITLE
Tilt doesn't respect custom dockerfile in docker-compose

### ISSUE THREAD

**Issue by quarkw** [tilt-dev/tilt#4094] opened 2021-01-20 03:04 UTC
### Expected Behavior
If a custom dockerfile is specified for building an image in a docker-compose folder used by Tilt, Tilt should use that dockerfile when building the image

### Current Behavior
Tilt uses the default Dockerfile, even if a custom dockerfile is specified in the docker-compose file

### Steps to Reproduce
1. Create a docker-compose file, with a locally built image (tested with v3 docker-compose file)
2. Create a Dockerfile in the default location
3. Create a Dockerfile in a separate location. Link to this Dockerfile in the docker-compose configuration
2. Create a tiltfile that utilizes the docker-compose file
3. Use `tilt up`
4. The image will be built with the wrong Dockerfile

#### `tilt doctor` Output
```
$ tilt doctor
Tilt: v0.18.3, built 2021-01-05
System: darwin-amd64
---
Docker
- Host: [default]
- Version: 1.41
- Builder: 2
---
Kubernetes
- Env: none
- Context:
- Cluster Name: Unknown
- Namespace: default
- Container Runtime: unknown
- Version: Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
- Cluster Local Registry: none
---
```

**Comment by maiamcc** [comment] 2021-01-20 17:05
Hey @quarkw, thanks for the report! I can't seem to reproduce this: [here's my attempt at a repro case](https://github.com/tilt-dev/tilt/tree/4094-repro/integration/onedc), and when I `tilt up` in this directory, I see Tilt building the correct Dockerfile (i.e. `Dockerfile.real`, the one specified in the docker compose file: [see snapshot](https://cloud.tilt.dev/snapshot/AYCJw4AMdf3GZut5tUs=)).

Can you post your Tiltfile and docker-compose.yaml, and/or a minimal repro case for your issue? Thanks!

**Comment by quarkw** [comment] 2021-01-20 17:40
Sorry about that! Here's a repo with the repro

https://github.com/quarkw/tilt-issue-4094

I think the issue is when `docker_build` is used in the Tiltfile the context overrides not just the build context, but also the build dockerfile

**Comment by maiamcc** [comment] 2021-01-20 22:28
Ah, I see the problem. So the behavior you're seeing (the image is built from `./Dockerfile`) is what I would _expect_ -- a `docker_build` call in the Tiltfile overrides build instructions in the `docker-compose.yml`. If you just remove that call, you should see the behavior you expect.

If you need the `docker_build` call for some reason (e.g. you're setting `only`/`ignore` values, you're using `live_update`, etc.) I'm afraid you'll just need to pass the Dockerfile path into the `docker_build` call:
```
docker_build('quarkw/tilt-test', '.', dockerfile='./dev-tools/Dockerfile')
```
(If you want to avoid hardcoding the Dockerfile path, you might pull it directly out of your `docker-compose.yml` by reading in the yaml with [`read_yaml()`](https://docs.tilt.dev/api.html#api.read_yaml).)

I totally get why you would expect the values in dc.yaml to take precedence -- imho it's one of those cases where there's no  solution to "which settings take precedence over which other settings" that wouldn't leave some user confused :-/

**Comment by quarkw** [comment] 2021-01-20 22:47
I definitely understand the issue with ambiguity

Here’s my reasoning for why I expected other behavior:
In the docs, that second arg for `docker_build` is labeled as “context”. In docker compose v2 and v3, “context” is a sub configuration of “build”, separate from “dockerfile” I think it would be more semantically correct labeled as “build”. 

Also the `read_yaml` tip is useful!

**Comment by maiamcc** [comment] 2021-01-22 22:42
Ah thanks for explaining, that makes sense. It might be that this use of `docker_build` (i.e. "here's the function that's responsible for all of the settings building your image") and/or its defaults make more sense when you're familiar with how the function is used in a Tilt+k8s context? Anyway, this is definitely something for us to chew on.

In the meantime, I'm going to close this ticket because your immediate issue is resolved, but let us know if you run into any more problems!

**Closed by maiamcc** 2021-01-22 22:42 UTC
Labels: bug
