### ISSUE TITLE
Allow running `tilt up` in detached mode

### ISSUE THREAD

**Issue by joeblubaugh** [tilt-dev/tilt#6194] opened 2023-08-16 07:00 UTC
## Describe the Feature You Want
I'm using tilt in CI and I'd like to be able to use the same shell to execute several steps:
1. Start tilt
2. `tilt wait` for a resource to be ready
3. Run a command that communicates with the resource.

Because I only have a single shell available in my CI system, I'd like to start up tilt without leaving the shell occupied. Right now this doesn't seem possible.

### Why Do You Want This?
I want to use tilt in Github workflows, which only provide a single runner for a job, and multiple runners cannot communicate. I need to be able to run tilt up without blocking the shell, similar to `docker run -d`

I've tried `tilt < /dev/null up &` to try and run tilt in the background, but it somehow steals stdin anyway, and my OS suspends the command.

**Comment by joeblubaugh** [comment] 2023-08-16 07:07
After going and reading `internal/cli/up.go` I noticed Tilt is also doing interesting things with stdout, so I redirected stdout as well. This serves my current use-case just fine, but a detached mode, followed with a `tilt down` command would be more ergonomic for me.

`tilt < /dev/null > /dev/null up &` works for now

**Comment by nicks** [comment] 2023-08-16 14:17
thanks for the feature request! marking this as a duplicate of https://github.com/tilt-dev/tilt/issues/4288

**Closed by nicks** 2023-08-16 14:17 UTC
Labels: enhancement
