### ISSUE TITLE
image garbage collection do not remove image from local docker

### ISSUE THREAD

**Issue by albaquarto** [tilt-dev/tilt#6199] opened 2023-08-17 18:01 UTC
I recently change my minikube node container runtime from docker to cri-o. My previous configuration for docker_prune was  docker_prune_settings(disable=False, keep_recent=1, num_builds=1) and it worked fine when tilt built images inside minikube but now  Tilt build the images in my host and the  images are not pruned as I expected. The garbage collector run immediatly after build or anyway before the prev pod is removed and the old image is not deleted. if I try to run pruner from cli lways 0 images are removed also if all of them are not used.

Tilt: v0.33.4, built 2023-08-11
System: linux-amd64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 24.0.5
- API Version: 1.43
- Builder: 2
- Compose Version: v2.20.2
---
Kubernetes
- Env: minikube
- Context: minikube
- Cluster Name: minikube
- Namespace: default
- Container Runtime: cri-o
- Version: v1.26.3
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: 59c4e28af87ce42124bac00a56bf63fa
- Repo: XrQ8ju9xFJcgiOPtEjARMg==
#6196

**Comment by nicks** [comment] 2023-12-04 17:53
as pointed out in https://github.com/tilt-dev/tilt/issues/6196, tilt will not delete images in use. closing this as working as intended.

**Closed by nicks** 2023-12-04 17:53 UTC
Labels: bug
