### ISSUE TITLE
UI resource stays yellow after readiness probe re-succeed (after a failure)

### ISSUE THREAD

**Issue by erickhun** [tilt-dev/tilt#6473] opened 2024-11-20 11:09 UTC
### Expected Behavior
After fixing the health-check, the ui resource should turn from yellow to green.

### Current Behavior
It stays yellow, even though I curl with a 200  the health-check endpoint. 

### Steps to Reproduce
1. Make readiness probe fail (resource turns yellow)
2. fix the healtcheck (resource turns green)
#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.33.21, built 2024-11-08
System: darwin-arm64
---
Docker
- Host: unix:///Users/eric/.orbstack/run/docker.sock
- Server Version: 27.3.1
- API Version: 1.47
- Builder: 2
- Compose Version: v2.29.7
---
Kubernetes
- Env: orbstack
- Context: orbstack
- Cluster Name: orbstack
- Namespace: default
- Container Runtime: docker
- Version: v1.29.3+orb1
- Cluster Local Registry: none
```

#### About Your Use Case

**What is interesting, is that if I change it liveness to readiness probes, the button gets back to green (from gray) correctly.** 

Here the liveness probe, and `tilt get uiresources` for the "original" , "broken", and "after fix" states

Liveness probe: 

```
  livenessProbe:
    httpGet:
      path: /health-check
      port: 3000
    initialDelaySeconds: 15 
    periodSeconds: 10 
    timeoutSeconds: 2 
    failureThreshold: 1 
    successThreshold: 1 
```

Original state (first start, green) : 

```
$tilt get uiresources core-api -o yaml

apiVersion: tilt.dev/v1alpha1
kind: UIResource
metadata:
  annotations:
    tilt.dev/resource: core-api
  creationTimestamp: "2024-11-20T09:24:35Z"
  labels:
    backend: backend
  name: core-api
  ownerReferences:
  - apiVersion: tilt.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Tiltfile
    name: (Tiltfile)
    uid: 5b5ddddd-cd7e-4e3b-a08f-7deda27403fe
  resourceVersion: "3166"
  uid: e3218b11-789c-4497-8520-ee40297d94ca
spec: {}
status:
  buildHistory:
  - finishTime: "2024-11-20T10:53:19.693590Z"
    spanID: build:60
    startTime: "2024-11-20T10:53:16.521489Z"
  - finishTime: "2024-11-20T10:12:12.356280Z"
    spanID: build:51
    startTime: "2024-11-20T10:12:11.122283Z"
  conditions:
  - lastTransitionTime: "2024-11-20T10:53:19.694940Z"
    status: "True"
    type: UpToDate
  - lastTransitionTime: "2024-11-20T10:53:38.542807Z"
    status: "True"
    type: Ready
  disableStatus:
    disabledCount: 0
    enabledCount: 1
    sources:
    - configMap:
        key: isDisabled
        name: core-api-disable
    state: Enabled
  endpointLinks:
  - url: https://authentication.local.comp.com
  k8sResourceInfo:
    allContainersReady: true
    displayNames:
    - core-api:service
    - core-api:deployment
    podCreationTime: "2024-11-20T10:53:19Z"
    podName: core-api-9c9c9d7f5-hcd5v
    podStatus: Running
    podUpdateStartTime: null
    spanID: pod:core-api:core-api-9c9c9d7f5-hcd5v
  lastDeployTime: "2024-11-20T10:53:19.693590Z"
  order: 11
  pendingBuildSince: null
  runtimeStatus: ok
  specs:
  - id: image:comp-mono-core-api:local-build
    type: image
  - id: k8s:core-api
    type: k8s
  updateStatus: ok
  ```

 " Broken State" , when I add an error on purpose and break the healtcheck: 
  ```
  apiVersion: tilt.dev/v1alpha1
kind: UIResource
metadata:
  annotations:
    tilt.dev/resource: core-api
  creationTimestamp: "2024-11-20T09:24:35Z"
  labels:
    backend: backend
  name: core-api
  ownerReferences:
  - apiVersion: tilt.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Tiltfile
    name: (Tiltfile)
    uid: 5b5ddddd-cd7e-4e3b-a08f-7deda27403fe
  resourceVersion: "3242"
  uid: e3218b11-789c-4497-8520-ee40297d94ca
spec: {}
status:
  buildHistory:
  - finishTime: "2024-11-20T10:53:19.693590Z"
    spanID: build:60
    startTime: "2024-11-20T10:53:16.521489Z"
  - finishTime: "2024-11-20T10:12:12.356280Z"
    spanID: build:51
    startTime: "2024-11-20T10:12:11.122283Z"
  conditions:
  - lastTransitionTime: "2024-11-20T10:53:19.694940Z"
    status: "True"
    type: UpToDate
  - lastTransitionTime: "2024-11-20T10:53:38.542807Z"
    status: "True"
    type: Ready
  disableStatus:
    disabledCount: 0
    enabledCount: 1
    sources:
    - configMap:
        key: isDisabled
        name: core-api-disable
    state: Enabled
  endpointLinks:
  - url: https://authentication.local.comp.com
  k8sResourceInfo:
    allContainersReady: true
    displayNames:
    - core-api:service
    - core-api:deployment
    podCreationTime: "2024-11-20T10:53:19Z"
    podName: core-api-9c9c9d7f5-hcd5v
    podRestarts: 3
    podStatus: Running
    podUpdateStartTime: null
    spanID: pod:core-api:core-api-9c9c9d7f5-hcd5v
  lastDeployTime: "2024-11-20T10:53:19.693590Z"
  order: 11
  pendingBuildSince: null
  runtimeStatus: ok
  specs:
  - id: image:comp-mono-core-api:local-build
    type: image
  - id: k8s:core-api
    type: k8s
  updateStatus: ok
  ```

  After I fix the healtchcheck: 

  ```
  apiVersion: tilt.dev/v1alpha1
kind: UIResource
metadata:
  annotations:
    tilt.dev/resource: core-api
  creationTimestamp: "2024-11-20T09:24:35Z"
  labels:
    backend: backend
  name: core-api
  ownerReferences:
  - apiVersion: tilt.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Tiltfile
    name: (Tiltfile)
    uid: 5b5ddddd-cd7e-4e3b-a08f-7deda27403fe
  resourceVersion: "3247"
  uid: e3218b11-789c-4497-8520-ee40297d94ca
spec: {}
status:
  buildHistory:
  - finishTime: "2024-11-20T10:53:19.693590Z"
    spanID: build:60
    startTime: "2024-11-20T10:53:16.521489Z"
  - finishTime: "2024-11-20T10:12:12.356280Z"
    spanID: build:51
    startTime: "2024-11-20T10:12:11.122283Z"
  conditions:
  - lastTransitionTime: "2024-11-20T10:53:19.694940Z"
    status: "True"
    type: UpToDate
  - lastTransitionTime: "2024-11-20T10:53:38.542807Z"
    status: "True"
    type: Ready
  disableStatus:
    disabledCount: 0
    enabledCount: 1
    sources:
    - configMap:
        key: isDisabled
        name: core-api-disable
    state: Enabled
  endpointLinks:
  - url: https://authentication.local.comp.com
  k8sResourceInfo:
    allContainersReady: true
    displayNames:
    - core-api:service
    - core-api:deployment
    podCreationTime: "2024-11-20T10:53:19Z"
    podName: core-api-9c9c9d7f5-hcd5v
    podRestarts: 4
    podStatus: Running
    podUpdateStartTime: null
    spanID: pod:core-api:core-api-9c9c9d7f5-hcd5v
  lastDeployTime: "2024-11-20T10:53:19.693590Z"
  order: 11
  pendingBuildSince: null
  runtimeStatus: ok
  specs:
  - id: image:comp-mono-core-api:local-build
    type: image
  - id: k8s:core-api
    type: k8s
  updateStatus: ok
  ```

**Comment by nicks** [comment] 2024-11-21 02:47
thanks for the report!

The short (unfortunate) answer is that this is working as designed. 

The warning in the tilt UI isn't related to the healthcheck -- it means that tilt saw the container restarting. But it doesn't really have a good way to tell why the container restarted, or that your changes fixed the restart. Note that you can clear the warning by clicking 'clear logs'.

i'm going to mark this as a duplicate of https://github.com/tilt-dev/tilt/issues/3483 -- though open to suggestions on how to improve this.

**Closed by nicks** 2024-11-21 02:47 UTC
Labels: bug
