### ISSUE TITLE
Refusing to run 'local' because default might be a production kube context in Tiltfile without k8s resources

### ISSUE THREAD

**Issue by rpocase** [tilt-dev/tilt#3615] opened 2020-07-24 19:45 UTC
I have a Tiltfile that does not interact with k8s in any way. In this use case, it only uses compose and docker_build, but I could be using tilt as a fancy `inotify`. If I have a KUBECONFIG in a default path (e.g. `~/.kube/config`), it will refuse to run `local` commands without `allowed_k8s_contexts`). Ideally, tilt should only care to run this check this if any `k8s` resources are declared.

**Comment by victorwuky** [comment] 2020-07-27 12:38
@nicks : Should we consider this a bug?

**Comment by nicks** [comment] 2020-07-27 14:49
Thanks! Ya, this is tricky. See discussion here: https://github.com/tilt-dev/tilt/issues/3066

The problem is that when the local() is executed, Tilt doesn't have any way to know if there are any k8s resources declared yet. We generally see people work around this by doing `allow_k8s_context(k8s_context())`

Marking this as a dupe of https://github.com/tilt-dev/tilt/issues/3066

**Closed by nicks** 2020-07-27 14:49 UTC
