### ISSUE TITLE
Port forwarding a service

### ISSUE THREAD

**Issue by Vanderscycle** [tilt-dev/tilt#6002] opened 2022-12-29 23:01 UTC
## Describe the Feature You Want
Essentially I was hoping for a tilt function executing the following: `kubectl port-forward service/argocd-server -n default 8082:443` for ,by example, argocd. I couldn't find anything in tilt docs that would allow me to write the command in the tiltfile instead of using a terminal.

### Current Behavior
The current behavior doesn't produce the result that I want.
```bash
load('ext://helm_resource', 'helm_resource', 'helm_repo')
helm_repo('argo', 'https://argoproj.github.io/argo-helm')
helm_resource('argocd', 'argo/argo-cd')
k8s_resource('argocd',labels="monitoring",port_forwards='8080:443') # I want to target the service and not deployment.
```

### Why Do You Want This?
Tilt is amazing and I have been working with other non-devops engineers to integrate tilt inside their development workflow so that we have a localhost development workflow that is similar to the production infrastructure where the final code must live in.

**Additional context**
N/A

Thank you for the good work

**Comment by nicks** [comment] 2023-01-03 18:25
thanks for the report! I'm going to mark this as a duplicate of https://github.com/tilt-dev/tilt/issues/5944, which is about the general problem where helm_resource deploys lots of different types of pods and Tilt isn't sure how to summarize them.

Workarounds right now:

- Create a separate local_resource to do the port-forwarding, here are some examples: https://docs.tilt.dev/local_resource.html#serve_cmd
- Modify the k8s_resource to only track the argocd-server pods, which will look something like:

```
k8s_resource('argocd', extra_pod_selectors={"app.kubernetes.io/name": "argocd-server"}, discovery_strategy="selectors-only")
```

**Closed by nicks** 2023-01-03 18:25 UTC
Labels: enhancement

**Comment by Vanderscycle** [comment] 2023-01-03 18:29
@nicks Thank you for the help and the workaround.
