### ISSUE TITLE
kubectl exec resource to init pod

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt#3923] opened 2020-11-13 14:59 UTC
MrNomates in the Tilt channel suggested this feature:

> I'm using HashiCorp Vault as a backing service in my app and I need to configure it after installing its chart. I basically have to do kubectl exec -it ${POD} -- vault secrets enable -path=gw-keys kv-v2 where ${POD} has to be computed with kubectl get .... Is making calls to local() the best/only way to do this? Isn't there a kubectl/helm-aware alternative that allows me to do something like kubectl_exec(app='vault', 'vault secrets enable -path=gw-keys kv-v2') , where app is the annotation for the app in the pod.

I really like this idea! This might make a good tilt extension https://github.com/tilt-dev/tilt-extensions

**Comment by nicks** [comment] 2020-11-13 15:13
(note that you can currently do this with a local_resource that depends on the service, but you need to stitch together the kubectl exec to the right pod yourself)

**Comment by lizzthabet** [comment] 2022-04-20 18:35
i'm going to close this as a duplicate of #4818, but it can be reopened if the button approach described in that issue doesn't meet the use case appropriately!

**Closed by lizzthabet** 2022-04-20 18:35 UTC
Labels: enhancement
