### ISSUE TITLE
Add option to disable pushing images manually

### ISSUE THREAD

**Issue by zaro** [tilt-dev/tilt#4587] opened 2021-05-26 10:45 UTC
## Describe the Feature You Want
Right now tilt disables push only if k8s is minikube ( and few others). I've made a setup with `k3s --docker` which basically makes k3s to use the already installed docker daemon. This leads to a push which is not needed at all because after the build I always the get message ` Container image "..." already present on machine`. This is normal as both k3s and tilt use the same docker daemon.

### Current Behavior
Needless push if using tilt with `k3s  --docker` as dev cluster.

### Why Do You Want This?
I would like to skip waiting for a push which is not needed anyway.

**Comment by nicks** [comment] 2021-06-07 16:59
thanks for the report! I'm going to mark this as a duplicate of https://github.com/tilt-dev/tilt/issues/3654, since i think they're basically the same issue

**Closed by nicks** 2021-06-07 16:59 UTC
Labels: enhancement
