### ISSUE TITLE
Support for multi-cluster resource

### ISSUE THREAD

**Issue by ShreyanshMehta** [tilt-dev/tilt#6294] opened 2024-01-17 16:02 UTC
#### There is a requirement where I want to deploy and watch a pod running in a different kind cluster. The deployment depends on the resources running in the current context. As of today, it is not possible. 

We can have something similar to `k8s_attach` where developers can attach to a pod running in the current context which is managed outside the Tilt. 

We may introduce something similar to `k8s_attach` which takes `kubeconfig` file path and `context` as an input to attach to a pod running in a different kind cluster.

**Comment by nicks** [comment] 2024-01-17 16:57
thanks for the report! marking this as a duplicate of https://github.com/tilt-dev/tilt/issues/3856

**Closed by nicks** 2024-01-17 16:57 UTC
Labels: enhancement
