### ISSUE TITLE
`docker_build` is not respecting `.dockerignore`

### ISSUE THREAD

**Issue by garyng** [tilt-dev/tilt#5745] opened 2022-04-28 17:23 UTC
### Expected Behavior

`docker_build` should respect `.dockerignore`.

### Current Behavior

`docker_build` seems to ignore `.dockerignore` causing very long build if there are a lot of ignored files (eg: `node_modules`). I did some search on GitHub and found this: https://github.com/tilt-dev/tilt/pull/5416, which might be relevant?

### Steps to Reproduce

1. Clone https://github.com/tilt-dev/tilt-avatars
1. Run `tilt up`
1. Observe the time for `[background] read source files`, in this case it was `[background] read source files 61.67kB [done: 2.789s]`
```
STEP 1/3 — Building Dockerfile: [tilt-avatar-web]
Building Dockerfile for platform linux/amd64:
  FROM node:16-bullseye-slim
  
  ENV YARN_CACHE_FOLDER=/cache/yarn
  
  WORKDIR /app
  
  # install dependencies
  COPY web/package.json web/yarn.lock ./
  RUN --mount=type=cache,target=/cache/yarn \
    yarn install
  
  # copy app source
  COPY web/ ./
  
  CMD ["yarn", "dev"]

     Building image
     [stage-0 1/5] FROM docker.io/library/node:16-bullseye-slim@sha256:9ae59bd83f46c6e6b83c0552fdfb0da00b3df50542b80ec818c658438cc61af1 68.68MB / 68.68MB [done: 58.791s]
     [background] read source files 61.67kB [done: 2.789s]
     [stage-0 2/5] WORKDIR /app [done: 10.288s]
     [stage-0 3/5] COPY web/package.json web/yarn.lock ./ [done: 5.699s]
     [stage-0 4/5] RUN --mount=type=cache,target=/cache/yarn   yarn install
       → yarn install v1.22.18
       → [1/4] Resolving packages...
       → [2/4] Fetching packages...
       → [3/4] Linking dependencies...
       → [4/4] Building fresh packages...
       → Done in 27.73s.
     [stage-0 4/5] RUN --mount=type=cache,target=/cache/yarn   yarn install [done: 38.546s]
     [stage-0 5/5] COPY web/ ./ [done: 4.13s]
     exporting to image [done: 13.678s]
```

1. Run `npm install` inside `web`
    (I installed a few more packages to get a bigger `node_modules`: `npm i bootstrap lodash chalk request commander react express debug async fs-extra moment bluebird underscore vue axios tslib glob rxjs babel-core yeoman-generator`)
1. Run `tilt up`
1.  Observe the time for `[background] read source files`, this time it was `[background] read source files 384.47kB [done: 3m37.945s]`

```
STEP 1/3 — Building Dockerfile: [tilt-avatar-web]
Building Dockerfile for platform linux/amd64:
  FROM node:16-bullseye-slim
  
  ENV YARN_CACHE_FOLDER=/cache/yarn
  
  WORKDIR /app
  
  # install dependencies
  COPY web/package.json web/yarn.lock ./
  RUN --mount=type=cache,target=/cache/yarn \
    yarn install
  
  # copy app source
  COPY web/ ./
  
  CMD ["yarn", "dev"]

     Building image
     [stage-0 1/5] FROM docker.io/library/node:16-bullseye-slim@sha256:9ae59bd83f46c6e6b83c0552fdfb0da00b3df50542b80ec818c658438cc61af1
     [background] read source files 384.47kB [done: 3m37.945s]
     [stage-0 2/5] WORKDIR /app [cached]
     [stage-0 3/5] COPY web/package.json web/yarn.lock ./ [done: 1.644s]
     [stage-0 4/5] RUN --mount=type=cache,target=/cache/yarn   yarn install
       → yarn install v1.22.18
       → [1/4] Resolving packages...
       → [2/4] Fetching packages...
       → [3/4] Linking dependencies...
       → warning " > bootstrap@5.1.3" has unmet peer dependency "@popperjs/core@^2.10.2".
       → [4/4] Building fresh packages...
       → success Saved lockfile.
       → Done in 36.24s.
     [stage-0 4/5] RUN --mount=type=cache,target=/cache/yarn   yarn install [done: 40.442s]
     [stage-0 5/5] COPY web/ ./ [done: 2.056s]
     exporting to image [done: 4.975s]
```

#### `tilt doctor` Output

```
$ tilt doctor
...

Tilt: v0.27.3, built 2022-04-22
System: linux-amd64
---
Docker
- Host: [default]
- Server Version: 20.10.14
- API Version: 1.41
- Builder: 2
- Compose Version: v1.29.2 (build 5becea4c)
---
Kubernetes
- Env: docker-desktop
- Context: docker-desktop
- Cluster Name: docker-desktop
- Namespace: default
- Container Runtime: docker
- Version: v1.22.5
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-out
- Machine: 2e40bfee00900c30e704f0a120347b62
- Repo: 3oHS3Sdl6tpcRYbbMgRgBg=
```

**Comment by nicks** [comment] 2022-04-28 18:20
Hmmm...that's odd. I wasn't able to reproduce this. 

what happens if you modify the dockerfile to do:

```
COPY web/node_modules web/package.json web/yarn.lock ./
```

do you get an error like this?

```
          web │      [stage-0 3/5] COPY web/node_modules web/package.json web/yarn.lock ./
          web │      
          web │      ERROR IN: [stage-0 3/5] COPY web/node_modules web/package.json web/yarn.lock ./
          web │ 
          web │ ERROR: Build Failed: ImageBuild: "/web/node_modules" not found
```

**Comment by nicks** [comment] 2022-04-28 18:21
i notice that you're using the docker-desktop linux beta, so let me try installing that and see if it changes things.

**Comment by garyng** [comment] 2022-04-28 19:18
Oh, I'm not running Docker Desktop on Linux - I'm running a Docker-from-Docker setup, `tilt` is in the container, and the docker socket is forwarded from Docker Desktop on **Windows**.

> what happens if you modify the dockerfile to do:
> 
> ```
> COPY web/node_modules web/package.json web/yarn.lock ./
> ```
> 
> do you get an error like this?
> 
> ```
>           web │      [stage-0 3/5] COPY web/node_modules web/package.json web/yarn.lock ./
>           web │      
>           web │      ERROR IN: [stage-0 3/5] COPY web/node_modules web/package.json web/yarn.lock ./
>           web │ 
>           web │ ERROR: Build Failed: ImageBuild: "/web/node_modules" not found
> ```

Yeap, I got an error:

```
STEP 1/3 — Building Dockerfile: [tilt-avatar-web]
Building Dockerfile for platform linux/amd64:
  FROM node:16-bullseye-slim
  
  ENV YARN_CACHE_FOLDER=/cache/yarn
  
  WORKDIR /app
  
  # install dependencies
  COPY web/node_modules web/package.json web/yarn.lock ./
  RUN --mount=type=cache,target=/cache/yarn \
    yarn install
  
  # copy app source
  COPY web/ ./
  
  CMD ["yarn", "dev"]


     Building image
     [stage-0 1/5] FROM docker.io/library/node:16-bullseye-slim@sha256:9ae59bd83f46c6e6b83c0552fdfb0da00b3df50542b80ec818c658438cc61af1
     [background] read source files 384.44kB [done: 59.125s]
     [stage-0 2/5] WORKDIR /app [cached]
     [stage-0 3/5] COPY web/node_modules web/package.json web/yarn.lock ./
     
     ERROR IN: [stage-0 3/5] COPY web/node_modules web/package.json web/yarn.lock ./

Build Failed: ImageBuild: "/web/node_modules" not found
```

**Comment by nicks** [comment] 2022-04-28 19:23
when you say 'tilt is in the container', can you share a bit more about how you have tilt set up? so you're not using WSL, you're running tilt inside docker-desktop?

**Comment by nicks** [comment] 2022-04-28 19:36
The error message makes this even weirder. let me try to set up a windows machine with this setup and see what happens.

what about if you run:

```
DOCKER_BUILDKIT=1 docker build -f deploy/web.dockerfile .
```

does it take a long time to read source files then?

so the way buildkit (docker's new image builder) works is that the client sets up a small local file server, and the docker daemon  pulls those files up in the background. According to your error message, it's pulling the files up, but not copying them into the docker context. this might be a docker bug in the interop between docker-desktop windows.

**Comment by garyng** [comment] 2022-04-28 19:43
My host is a Windows machine and I'm using VSCode's [Remote Containers](https://code.visualstudio.com/docs/remote/containers), specifically the `Docker-from-Docker Compose` configuration: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/docker-from-docker-compose.

 `tilt` (`docker`, `kubectl`, etc) is installed inside the Linux container, the `docker` socket is mounted into the container as well. So effectively, the docker inside the container is actually from the Docker Desktop running in the host Windows machine.

Give me some time, I'll try to create a repo your testing.

**Comment by milas** [comment] 2022-04-28 20:12
The ignore logic is definitely working, as the transferred size is always < 400 KB. I think the background sync job walking the file tree might be very slow. On Windows (NTFS), `node_modules` folders can often be problematic due to the sheer number of nested directories + files in them.

The VSCode docs [recommend having your source code on the WSL filesystem](https://code.visualstudio.com/blogs/2020/07/01/containers-wsl#_working-with-containers) rather than Windows:
> While you can access source code from both Windows and the WSL 2 filesystem when using the WSL 2 engine, we recommend using the WSL 2 file system because [performance is much better](https://www.docker.com/blog/docker-desktop-wsl-2-best-practices/). Since the performance is better when using the filesystem inside WSL 2, let's walk through how to use it.

**Comment by garyng** [comment] 2022-04-28 20:17
> ... I think the background sync job walking the file tree might be very slow ...

Yeah, I think this might be the reason as well... Is it possible to not walk the content of an ignored directory?

--- 

WSL2 have too much issues on my local and I just gave up on using it...

**Comment by garyng** [comment] 2022-04-28 20:40
> The error message makes this even weirder. let me try to set up a windows machine with this setup and see what happens.
> 
> what about if you run:
> 
> ```
> DOCKER_BUILDKIT=1 docker build -f deploy/web.dockerfile .
> ```
> 
> does it take a long time to read source files then?
> 
> so the way buildkit (docker's new image builder) works is that the client sets up a small local file server, and the docker daemon pulls those files up in the background. According to your error message, it's pulling the files up, but not copying them into the docker context. this might be a docker bug in the interop between docker-desktop windows.

@nicks `DOCKER_BUILDKIT=1 docker build -f deploy/web.dockerfile .` runs pretty fast:
```
[+] Building 5.8s (7/9)                                                                                 
 => [internal] load build definition from web.dockerfile                                           0.8s
 => => transferring dockerfile: 36B                                                                0.0s
 => [internal] load .dockerignore                                                                  1.1s
 => => transferring context: 34B                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:16-bullseye-slim                           1.5s
 => [stage-0 1/5] FROM docker.io/library/node:16-bullseye-slim@sha256:9ae59bd83f46c6e6b83c0552fdf  0.0s
 => [internal] load build context                                                                  0.4s
 => => transferring context: 489B                                                                  0.0s
 => CACHED [stage-0 2/5] WORKDIR /app                                                              0.0s
 => CACHED [stage-0 3/5] COPY web/package.json web/yarn.lock ./                                    0.0s
 => [stage-0 4/5] RUN --mount=type=cache,target=/cache/yarn   yarn install                         2.3s
```

Does this means that this is not a Docker's/Windows file system's issue?

**Comment by nicks** [comment] 2022-04-28 20:55
ooh @milas that's a good call.

it's probably a combination of things.

docker has a fast path (where it can skip the whole directory) and a slow path (where it has to stat the whole directory tree).

there's a bunch of different ways you can kick it down the slow path if you're not careful.

and in this case, the slow path is pathologically slow, due to the way you're setting up the filesystem across OS boundaries.

i've been wondering for a while if we should fork the buildkit fileserver so that we can fix problems like this, but let me talk to the buildkit people a bit about the best way to resolve this.

**Comment by garyng** [comment] 2022-04-29 02:10
Here is the repo: https://github.com/garyng/tilt-docker-issue-5745. Open the folder in VSCode, and it should prompt to reopen it in container.

**Closed** 2022-05-05 18:17 UTC
Labels: bug
